baseurl = "/"
languageCode = "en-gb"
languageLang = "en"
title = "Craig Childs - Full Stack Developer"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
  Author = "Craig Childs"
  Description = "Hi, my name is Craig Childs! I'm a remote Full-Stack Web Developer from the UK."
  Url = "https://craigchilds.me"
  Keywords = "web, developer, full, stack, php, laravel, go, blog, craig childs, code, remote, ruby, rails, shopify"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4

[related]
  treshold = 80
  includeNewer = false
  toLower = false

  [[related.indices]]
      name = "keywords"
      weight = 100
  [[related.indices]]
      name = "date"
      weight = 10
