backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "site/static/media"
public_folder: "/media"
site_url: "https://craigchilds.dev"
display_url: "https://craigchilds.dev"
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "site/content/_index.md"
        fields:
          - {label: Heading, name: heading, widget: string}
          - {label: Sub Heading, name: subheading, widget: string}
          - {label: Avatar, name: avatar, widget: image}
          - {label: Medium, name: medium, widget: string}
          - {label: Github, name: github, widget: string}
          - {label: Twitter, name: twitter, widget: string}
          - {label: Content, name: content, widget: markdown}